name: MSBuild

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 15

    strategy:
      matrix:
        operating-system: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Test - Win32
        run: |
          cd C:\Program Files (x86)\Microsoft Visual Studio\Installer
          for /f "usebackq tokens=*" %i IN (`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) DO @set vcdir=%i
          "%vcdir%\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          src\BuildALL.cmd

#      - name: "Build Changelog"
#        id: build_changelog
#        uses: mikepenz/release-changelog-builder-action@v2.4.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Release_${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          #body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: output\pkg\**\*.exe
